### ISSUE TITLE
CRUD-operations $set operator syntax

### ISSUE THREAD

**Issue by ghost** [leojavier/MongoDb-cheat-sheet#1]
CRUD-operations $set operator [https://github.com/leojavier/MongoDb-cheat-sheet/blob/master/1.0%20CRUD-operations.md#set-operator](url)
it seems that the syntax is diff from manual from mongodb.com [https://docs.mongodb.com/manual/tutorial/update-documents/#update-documents-in-a-collection](url)

```
{
  <update operator>: { <field1>: <value1>, ... },
  <update operator>: { <field2>: <value2>, ... },
  ...
}
```

**Comment by xieweijie** [comment]
> CRUD-operations $set operator [https://github.com/leojavier/MongoDb-cheat-sheet/blob/master/1.0%20CRUD-operations.md#set-operator](url)
> it seems that the syntax is diff from manual from mongodb.com [https://docs.mongodb.com/manual/tutorial/update-documents/#update-documents-in-a-collection](url)
> 
> ```
> {
>   <update operator>: { <field1>: <value1>, ... },
>   <update operator>: { <field2>: <value2>, ... },
>   ...
> }
> ```

I just notice that this repository is 2015...
